# Generated by Django 5.1.4 on 2024-12-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("main", "0003_remove_category_author_remove_task_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="category",
            field=models.ManyToManyField(to="main.category"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="task",
            field=models.ManyToManyField(to="main.task"),
        ),
    ]
