# Generated by Django 5.1.4 on 2024-12-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_category_remove_customuser_task"),
        ("main", "0006_remove_category_author_remove_task_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="categories",
            field=models.ManyToManyField(related_name="author", to="main.category"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tasks",
            field=models.ManyToManyField(related_name="author", to="main.task"),
        ),
    ]
