# Generated by Django 5.1.4 on 2024-12-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_categories_customuser_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tasks",
        ),
    ]
