# Generated by Django 5.0.6 on 2024-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_todoitem_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="image",
            field=models.ImageField(default=1, upload_to="todoimages"),
            preserve_default=False,
        ),
    ]
