# Generated by Django 5.1.4 on 2024-12-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="author",
        ),
        migrations.RemoveField(
            model_name="task",
            name="author",
        ),
    ]
