# Generated by Django 5.0.6 on 2024-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_todoitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="main/todoimages"),
        ),
    ]
