# Generated by Django 5.1.4 on 2024-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_task_delete_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="taskimages/"),
        ),
    ]
