# Generated by Django 5.1.4 on 2024-12-09 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_task_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
