# Generated by Django 5.1.4 on 2024-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_category_author_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="others", max_length=10),
        ),
    ]
