# Generated by Django 5.1.4 on 2024-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="text",
            new_name="name",
        ),
    ]
